trigger: 
  - main

pool: may-pool

stages:
  - stage: FirstStage
    displayName: Init
    jobs:
      - job: terraforminit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'pet.tfstate'


  - stage: SecondStage
    displayName: Plan
    jobs:
      - job: terraformplan
        steps:
             - task: TerraformTask@5
               inputs:
                 provider: 'azurerm'
                 command: 'init'
                 workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
                 backendServiceArm: 'may-sc'
                 backendAzureRmStorageAccountName: 'maystg12'
                 backendAzureRmContainerName: 'maycnt12'
                 backendAzureRmKey: 'pet.tfstate'

             - task: TerraformTask@5
               inputs:
                 provider: 'azurerm'
                 command: 'plan'
                 workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
                 environmentServiceNameAzureRM: 'may-sc'

  - stage: LastStage
    displayName: Apply
    jobs:
      - job: terraformapply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'pet.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'may-sc'


